{% set name = "Theano-PyMC" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5da6c2242ea72a991c8446d7fe7d35189ea346ef7d024c890397011114bf10fc

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - theano-cache = bin.theano_cache:main
  # ModuleNotFoundError: No module named 'numpy.distutils'
  # This project is archived by PyPI, but it is still used as a backend for pymc3.
  # Won`t fix py>311 compatibility issues which appeared in versioneer and cmodule.py.
  skip: true  # [py>311]

requirements:
  build:
  host:
    - pip
    - python
    - wheel
    - setuptools
    - numpy 1.26.4
  run:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - numpy >=1.9.1
    - scipy >=0.14
    - filelock

test:
  imports:
    - theano
  requires:
    - pip
  commands:
    - pip check
    - theano-cache help

about:
  home: https://github.com/pymc-devs/Theano-PyMC
  summary: An optimizing compiler for evaluating mathematical expressions. Theano-PyMC is a fork of the Theano library maintained by the PyMC developers.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Theano is a Python library that allows you to define, optimize, and efficiently evaluate
    mathematical expressions involving multi-dimensional arrays. It is built on top of NumPy.
  dev_url: https://github.com/pymc-devs/Theano-PyMC
  doc_url: https://theano-pymc.readthedocs.io

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - brandonwillard
  skip-lints:
    - compilers_must_be_in_build
    - patch_unnecessary
