{% set name = "Theano-PyMC" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5da6c2242ea72a991c8446d7fe7d35189ea346ef7d024c890397011114bf10fc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - theano-cache = bin.theano_cache:main

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - wheel
    - setuptools
    - numpy
  run:
    - python
    - numpy >=1.9.1
    - scipy >=0.14
    - filelock
    # 2021/10/20: Anaconda disable jax package (for faster optimization) 
    # until it gets available for all architectures

test:
  imports:
    - theano
  requires:
    - pip
  commands:
    - pip check
    - theano-cache help

about:
  home: https://github.com/pymc-devs/Theano-PyMC
  summary: An optimizing compiler for evaluating mathematical expressions. Theano-PyMC is a fork of the Theano library maintained by the PyMC developers.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Theano is a Python library that allows you to define, optimize, and efficiently evaluate
    mathematical expressions involving multi-dimensional arrays. It is built on top of NumPy.
  dev_url: https://github.com/pymc-devs/Theano-PyMC
  doc_url: https://theano-pymc.readthedocs.io

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - brandonwillard
