{% set version = "1.1.2" %}

package:
  name: theano-pymc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/T/Theano-PyMC/Theano-PyMC-{{ version }}.tar.gz
  sha256: 5da6c2242ea72a991c8446d7fe7d35189ea346ef7d024c890397011114bf10fc
  patches:

build:
  number: 0
  skip: True  # [py<36]
  entry_points:
    - theano-cache = bin.theano_cache:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.14
    #- six >=1.9.0
    #- pygpu >=0.7.0,<0.8
    #- jax  # [py>=37 and not win]
    - filelock

test:
  imports:
    - theano
  requires:
    - pip
  commands:
    - pip check
    - theano-cache help

about:
  home: https://github.com/pymc-devs/Theano-PyMC
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions. Theano-PyMC is a fork of the Theano library maintained by the PyMC developers.
  license_file: LICENSE.txt
  dev_url: https://github.com/pymc-devs/Theano-PyMC/
  doc_url: https://theano-pymc.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - brandonwillard
