{% set version = "1.0.15" %}

package:
  name: theano-pymc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/T/Theano-PyMC/Theano-PyMC-{{ version }}.tar.gz
  sha256: ba105ddf8d83bbbe159e9ad1d5128c400c6cffeda662eb77203f786ee816db09
  patches:

build:
  number: 0
  entry_points:
    - theano-cache = bin.theano_cache:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14
    - pygpu >=0.7.0,<0.8
    - jax  # [py>=37 and not win]
    - filelock

test:
  imports:
    - theano
  commands:
    - theano-cache help

about:
  home: https://github.com/pymc-devs/Theano-PyMC
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions. Theano-PyMC is a fork of the Theano library maintained by the PyMC developers.
  license_file: LICENSE.txt
  dev_url: https://github.com/pymc-devs/Theano-PyMC/
  doc_url: https://theano-pymc.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - twiecki
    - ericmjl
    - brandonwillard
